### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by slashtechno** [developeranaz/Ubuntu-Desktop-noVNC-Heroku-VPS#3]
Is there any way to add a form of authentication such as a password to noVNC?

**Comment by developeranaz** [comment]
I think this one is better than mine 
![THISONE](https://github.com/vital987/vubuntu)

**Comment by slashtechno** [comment]
> I think this one is better than mine ![THISONE](https://github.com/vital987/vubuntu)

@developeranaz It seems this is blocked by Heroku's terms of service.

**Comment by developeranaz** [comment]
> > I think this one is better than mine ![THISONE](https://github.com/vital987/vubuntu)
> 
> @developeranaz It seems this is blocked by Heroku's terms of service.

oh why this shit heroku keep blocking.

**Comment by developeranaz** [comment]
I think forking that repository and deploy with your own hosted github won't be a violation for some days.😊

**Comment by slashtechno** [comment]
I do not think I am going to be trying to deploy a desktop environment since it is a violation of Heroku's terms of service as well as being too much work for the actual usage that it has the potential for.
