### ISSUE TITLE
Blocked by heroku

### ISSUE THREAD

**Issue by 362227** [developeranaz/Ubuntu-Desktop-noVNC-Heroku-VPS#5]
Blocked by heroku

**Comment by developeranaz** [comment]
> Blocked by heroku

fork this repository, then click this linkj
https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https://github.com/362227/Ubuntu-Desktop-noVNC-Heroku-VPS

**Comment by 362227** [comment]
There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.

**Comment by 362227** [comment]
please fix

**Comment by developeranaz** [comment]
okey

**Comment by developeranaz** [comment]
This button will works for some hours or days.
 [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https://github.com/dev-extended/https-github.com-developeranaz-Ubuntu-Desktop-noVNC-Heroku-VPS-tree-ex)  heroku will set policy violation for this button too deploy as fast as you can

**Comment by 362227** [comment]
great
